"""Database creation

Revision ID: 33574db0f179
Revises: 
Create Date: 2023-12-03 15:14:53.758351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33574db0f179'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                sa.Column('id', sa.Integer(), nullable=False),
                sa.Column('name', sa.String(), nullable=False),
                sa.Column('permissions', sa.JSON(), nullable=True),
                sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
                sa.Column('id', sa.Integer(), nullable=False),
                sa.Column('email', sa.String(), nullable=False),
                sa.Column('username', sa.String(), nullable=False),
                sa.Column('password', sa.String(), nullable=False),
                sa.Column('reqistered_at', sa.TIMESTAMP(), nullable=True),
                sa.Column('role_id', sa.Integer(), nullable=True),
                sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
